### ISSUE TITLE
[2023.11.12] 20주차 스터디

### ISSUE THREAD

**Issue by pknujsp** [pknu-wap/android-blog-study#5]
벌써 20 주차네요. 반년이나 지난 게 안 믿겨요

**Comment by SeongHoonC** [comment]
이슈 작성해주셔서 감사합니다ㅎㅎ

**Comment by Zepelown** [comment]
[SQLite와 RoomDB](https://namamim.tistory.com/16)

**Comment by SeongHoonC** [comment]
[앱 재설치 시 크래시 발생(EncryptedSharedPreferences )](https://seonghoonc.tistory.com/40)

**Comment by jeongjaino** [comment]
[Android Compose : SideEffect Handler(1)](https://jeongjaino.tistory.com/68)

**Comment by jeongjaino** [comment]
아니,,, 벌써 반년이나 했다고요? 시간 너무 빠르다

**Comment by pknujsp** [comment]
[코루틴에서의 예외 처리](https://pknujsp.github.io/kotlin/coroutines/2023/11/12/%EC%BD%94%EB%A3%A8%ED%8B%B4%EC%97%90%EC%84%9C%EC%9D%98-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC.html)

**Comment by tgyuuAn** [comment]
[컴포즈에서 Composable 의 높이, 너비 측정 정책 및 측정하는 방법](https://blog.naver.com/tgyuu_/223262948277)
