### ISSUE TITLE
[2023.11.26] 22주차 스터디

### ISSUE THREAD

**Issue by pknujsp** [pknu-wap/android-blog-study#7]

**Comment by SeongHoonC** [comment]
불참 (코테 및 Devfest 발표준비)

**Comment by Zepelown** [comment]
불참 (개인 사정)

**Comment by tgyuuAn** [comment]
[Compose로 커스텀 달력 만들기 ! 제 20시간의 노력을 봐주실래요 ..? ](https://blog.naver.com/tgyuu_/223276267459)

**Comment by jeongjaino** [comment]
[Hackathon : Retrofit2 Multipart Annotation 그리고 모배디 해커톤 후기](https://jeongjaino.tistory.com/70)

**Comment by pknujsp** [comment]
[빈혈 도메인 모델, 쓸모없는 유스케이스, 비대한 뷰모델에 대하여 DroidKnights 2023](https://pknujsp.github.io/android/2023/11/27/%EB%B9%88%ED%98%88-%EB%8F%84%EB%A9%94%EC%9D%B8-%EB%AA%A8%EB%8D%B8,-%EC%93%B8%EB%AA%A8%EC%97%86%EB%8A%94-%EC%9C%A0%EC%8A%A4%EC%BC%80%EC%9D%B4%EC%8A%A4,-%EB%B9%84%EB%8C%80%ED%95%9C-%EB%B7%B0%EB%AA%A8%EB%8D%B8%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC-DroidKnights-2023.html)
